In [1]:
import numpy as np
import pandas as pd
import random

import matplotlib.pyplot as plt
import seaborn as sns

from kaggle_environments import make, evaluate

In [ ]:
#Example of the simple agent
#0 - rock
#1 - paper
#2 - scissors

In [ ]:
# 1

In [2]:
%%writefile agent_1.py

# Всегда только бумага
def agent_1(observation, configuration):
    return 1

Writing agent_1.py


In [ ]:
# 2

In [3]:
%%writefile agent_2.py

# Всегда только ножницы
def agent_2(observation, configuration):
    return 2

Writing agent_2.py


In [ ]:
# 3

In [4]:
%%writefile agent_3.py

import numpy as np


# Рандомный знак
def agent_3(observation, configuration):
    return np.random.randint(0, 3)

Writing agent_3.py


In [5]:
# 4

In [6]:
%%writefile agent_4.py

# Остаток от деления номера шага на 3
def agent_4(observation, configuration):
    return observation['step'] % 3

Writing agent_4.py


In [7]:
# 5

In [8]:
%%writefile agent_5.py

import random


enemy_actions = {0: 0, 1: 0, 2: 0}


# Копирует самый частый бросок врага
def agent_5(observation, configuration):
    global enemy_actions

    if observation.step == 0:
        return random.randrange(0, configuration.signs)
    enemy_actions[observation.lastOpponentAction] += 1
    if enemy_actions[0] >= enemy_actions[1] and enemy_actions[0] >= enemy_actions[2]:
        return 1
    elif enemy_actions[1] >= enemy_actions[0] and enemy_actions[1] >= enemy_actions[2]:
        return 2
    else:
        return 0

Writing agent_5.py


In [9]:
# 6

In [10]:
%%writefile agent_6.py

import random


enemy_actions = []


# Копия рандомного броска врага из истории
def agent_6(observation, configuration):
    global enemy_actions
    
    if observation.step == 0:
        return random.randrange(0, configuration.signs)
    
    enemy_actions.append(observation.lastOpponentAction)
    
    return enemy_actions[random.randrange(0, len(enemy_actions))]

Writing agent_6.py


In [ ]:
# 7

In [11]:
%%writefile agent_7.py
import random


actions = [0, 1, 1, 2, 0, 2]


# Последовательно выбираем шаг из заданной стратегии
def agent_7(observation, configuration):
    global actions
    
    return actions[observation.step % len(actions)]

Writing agent_7.py


In [12]:
# 8

In [13]:
%%writefile agent_8.py

import random


last_2 = []
possible_actions = {0, 1, 2}


# Бросок, который не встречался в селф-истории за последние два хода
# Например, если два последних камень, то выбираем случайно между ножницы и бумага
def agent_8(observation, configuration):
    global last_2, possible_actions

    if observation.step < 2:
        action = random.randrange(0, configuration.signs)
        last_2.append(action)
        return action

    next_possible = possible_actions - set(last_2)
    next_action = random.choice(tuple(next_possible))
    last_2.append(next_action)
    last_2.pop(0)

    return next_action

Writing agent_8.py


In [14]:
# 9

In [15]:
%%writefile agent_9.py

import random


last_2 = []
possible_actions = {0, 1, 2}


# Бросок, который не встречался в истории врага за последние два хода 
# Например, если два последних камень, то выбираем случайно между ножницы и бумага
def agent_9(observation, configuration):
    global last_2, possible_actions
    
    if observation.step == 0:
        return random.randrange(0, configuration.signs)
    elif observation.step < 2:
        action = random.randrange(0, configuration.signs)
        last_2.append(observation.lastOpponentAction)
        return action
    
    next_possible = possible_actions - set(last_2)
    next_action = random.choice(tuple(next_possible))
    last_2.append(observation.lastOpponentAction)
    last_2.pop(0)
    
    return next_action

Writing agent_9.py


In [16]:
# 10

In [17]:
%%writefile agent_10.py

import random


our_last = None
our_reward_last = 0


# Если наш последний ход выиграл, то повторяем его же, 
# иначе копируем вражеский 
def agent_10(observation, configuration):
    global our_last, our_reward_last

    if observation.step == 0: # на нулевом шаге выбираем рандомно
        our_last = random.randrange(0, configuration.signs)
        return our_last

    if our_reward_last < observation.reward:
        return our_last

    our_reward_last = observation.reward
    our_last = observation.lastOpponentAction
    
    return our_last

Writing agent_10.py


In [18]:
# 11

In [19]:
%%writefile agent_11.py

import random


our_last = None
our_reward_last = 0


# Если наш последний ход выиграл, то копируем вражеский,
# иначе повторяем свой ход
def agent_11(observation, configuration):
    global our_last, our_reward_last

    if observation.step == 0:  # на нулевом шаге выбираем рандомно
        our_last = random.randrange(0, configuration.signs)
        return our_last

    if our_reward_last < observation.reward:
        our_last = observation.lastOpponentAction
        return our_last

    our_reward_last = observation.reward

    return our_last

Writing agent_11.py


In [20]:
# 12

In [21]:
%%writefile agent_12.py

import random


our_last = None
our_reward_last = 0


# Если наш последний ход выиграл, то повторяем его же,
# иначе копируем вражеский
def agent_12(observation, configuration):
    global our_last, our_reward_last

    if observation.step == 0: # на нулевом шаге выбираем рандомно
        our_last = random.randrange(0, configuration.signs)
        return our_last

    if our_reward_last < observation.reward:
        return our_last

    our_reward_last = observation.reward
    our_last = random.randrange(0, configuration.signs)
    
    return our_last

Writing agent_12.py


In [110]:
# 13

In [116]:
%%writefile agent_13.py
import random


actions = [0, 2, 1, 2, 0, 1]


# Последовательно выбираем шаг из заданной стратегии
def agent_13(observation, configuration):
    global actions
    
    return actions[observation.step % len(actions)]

Writing agent_13.py


# Проверка

Пусть каждый агент сыграет в каждым, посмотрим, какая стратегия покажет себя лучше всех

In [113]:
# Составим список агентов
list_agents = [f"agent_{i}.py" for i in range(1, 14)]
list_agents

['agent_1.py',
 'agent_2.py',
 'agent_3.py',
 'agent_4.py',
 'agent_5.py',
 'agent_6.py',
 'agent_7.py',
 'agent_8.py',
 'agent_9.py',
 'agent_10.py',
 'agent_11.py',
 'agent_12.py',
 'agent_13.py']

In [114]:
# Заготовка массива для баллов
scores = np.zeros((len(list_agents), len(list_agents)), dtype=int)
scores

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Во вложенном цикле пройдемся по всем комибнациям. Мы должны получить симметричную относительно главной диагонали матрицу. 

In [117]:
for i in range(scores.shape[0]):
    print(i)
    for j in range(scores.shape[1]):
        res = evaluate(
                    "rps",                                 
                    [list_agents[i], list_agents[j]],      # агенты
                    configuration={"episodeSteps": 50, 
                                   'tieRewardThreshold': 1 # Минимальная награда, необходимая 
                                                           # для достижения победы, а не ничьей
                                  }, 
#                     num_episodes=5
                )[0]
        scores[i][j] = np.sign(res[0])
        scores[j][i] = np.sign(res[1])

0
1
2
3
4
5
6
7
8
9
10
11
12


In [118]:
scores

array([[ 0, -1, -1,  1, -1,  1,  1,  1, -1,  1,  0,  1,  1],
       [ 1,  0,  1, -1, -1,  0, -1,  0, -1,  0,  1, -1, -1],
       [ 1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1],
       [-1,  1, -1,  0, -1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1, -1,  1, -1,  0,  0,  1, -1, -1, -1],
       [-1,  0,  1, -1, -1,  1, -1,  1, -1, -1,  0,  1,  1],
       [-1,  1, -1, -1,  1,  1,  0, -1,  1,  1,  1,  0,  0],
       [-1,  0,  1, -1,  0, -1,  1,  0,  1,  1, -1,  1, -1],
       [ 1,  1,  1, -1,  0,  1, -1, -1,  1,  1,  1,  1,  1],
       [-1,  0,  1, -1, -1,  1, -1, -1, -1,  1,  0, -1, -1],
       [ 0, -1, -1, -1,  1,  0, -1,  1, -1,  0,  1,  1,  1],
       [-1,  1, -1, -1,  1, -1,  0, -1, -1,  1, -1,  0,  0],
       [-1,  1, -1, -1,  1, -1,  0,  1, -1,  1, -1,  0,  0]])

In [119]:
scores.sum(axis=0)  # сумма побед и поражения

array([-3,  3, -1, -6, -3,  3, -2,  0, -4,  7,  2,  4,  2])

In [120]:
np.argmax(scores.sum(axis=0))  # индекс лучшей стратегии

9

In [121]:
scores.mean(axis=0) # среднее арифметическое побед и поражения

array([-0.23076923,  0.23076923, -0.07692308, -0.46153846, -0.23076923,
        0.23076923, -0.15384615,  0.        , -0.30769231,  0.53846154,
        0.15384615,  0.30769231,  0.15384615])

In [122]:
np.argmax(scores.mean(axis=0)) # индекс лучшей стратегии

9

In [123]:
# Теперь посчитаем только победы

In [124]:
wins = np.where(scores == 1, scores, 0)
wins

array([[0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0]])

In [125]:
wins.sum(axis=0)  # снова посчитаем суммы

array([4, 6, 6, 3, 4, 7, 4, 5, 4, 9, 6, 7, 6])

In [126]:
np.argmax(scores.sum(axis=0))  # индекс лучшей стратегии

9

# Итог
Стратегия 10 лучше всех (выше выводится 9, поскольку это индекс, 9+1 = 10 стратегия). Стратегия заключалась в следующем:
Если наш последний ход выиграл, то повторяем его же, 
иначе копируем вражеский 